# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import data_pb2 as data__pb2


class DataNumberStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getPhoneNumber = channel.unary_unary(
                '/DataNumber/getPhoneNumber',
                request_serializer=data__pb2.Text.SerializeToString,
                response_deserializer=data__pb2.Text.FromString,
                )


class DataNumberServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getPhoneNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataNumberServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getPhoneNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.getPhoneNumber,
                    request_deserializer=data__pb2.Text.FromString,
                    response_serializer=data__pb2.Text.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DataNumber', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataNumber(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getPhoneNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataNumber/getPhoneNumber',
            data__pb2.Text.SerializeToString,
            data__pb2.Text.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
